version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: idm-postgres
    environment:
      POSTGRES_USER: idm_user
      POSTGRES_PASSWORD: idm_password
      POSTGRES_DB: idm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: